"""Combined v1 API router."""
from __future__ import annotations

from fastapi import APIRouter

from app.api.v1 import admin, aaas, airspace_calendar, annotation_search, approval_templates, approvals, audit_export, auth, auth_2fa, auth_events, auth_reset, auth_sessions, auth_sso, ciio, community, community_bookmarks, community_likes, community_playbooks, compliance, copilot, copilot_workflows, crypto_sm2, detection_alerts, drones, frame_diff, geofence, health, marketplace_monetization, missions, model_marketplace as mm_router, officers, preflight, remoteid, scene_annotation, scene_frame, scene_job, scene_marketplace, scene_moderation, scenes, scenes_artifacts, scenes_upload, sim, streams, trajectory, uom, video_streams, vision_analytics, vision_copilot as vc_router, websocket
from app.services.metrics import router as metrics_router

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(auth.router)
api_router.include_router(auth_2fa.router)
api_router.include_router(auth_sso.router)
api_router.include_router(auth_events.router)
api_router.include_router(auth_reset.router)
api_router.include_router(auth_sessions.router)
api_router.include_router(approvals.router)
api_router.include_router(approval_templates.router)
api_router.include_router(airspace_calendar.router)
api_router.include_router(marketplace_monetization.router)
api_router.include_router(scene_annotation.router)
api_router.include_router(frame_diff.router)
api_router.include_router(scene_frame.router)
api_router.include_router(annotation_search.router)
api_router.include_router(aaas.router)
api_router.include_router(crypto_sm2.router)
api_router.include_router(audit_export.router)
api_router.include_router(ciio.router)
api_router.include_router(scenes.router)
api_router.include_router(scenes_upload.router)
api_router.include_router(scenes_artifacts.router)
api_router.include_router(scene_marketplace.router)
api_router.include_router(scene_moderation.router)
api_router.include_router(scene_job.router)
api_router.include_router(video_streams.router)
api_router.include_router(compliance.router)
api_router.include_router(officers.router)
api_router.include_router(vc_router.vision_router)
api_router.include_router(vision_analytics.router)
api_router.include_router(detection_alerts.router)
api_router.include_router(vc_router.copilot_router)
api_router.include_router(drones.router)
api_router.include_router(missions.router)
api_router.include_router(streams.router)
api_router.include_router(websocket.router)
api_router.include_router(copilot.router)
api_router.include_router(copilot_workflows.router)
api_router.include_router(sim.router)
api_router.include_router(trajectory.router)
api_router.include_router(uom.router)
api_router.include_router(preflight.router)
api_router.include_router(geofence.router)
api_router.include_router(remoteid.router)
api_router.include_router(community.router)
api_router.include_router(community_bookmarks.router)
api_router.include_router(community_likes.router)
api_router.include_router(community_playbooks.router)
api_router.include_router(mm_router.router)
api_router.include_router(admin.router)
api_router.include_router(metrics_router)

__all__ = ["api_router"]
